language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda create -n rnasee python=2.7;
      conda activate rnasee;
    
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      conda create -n rnasee python=3.5;
      conda activate rnasee;
    
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      conda create -n rnasee python=3.6;
      conda activate rnasee;
    
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
      conda create -n rnasee python=3.7;
      conda activate rnasee;
    fi

  - conda install pandas
  - conda install -c bioconda biopython viennarna
  - pip install codecov
  - codecov
  - codecov --token="3c966cf0-3df9-4bec-bbd2-2dd952019d6c"

  # Replace dep1 dep2 ... with your dependencies
  #- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION dep1 dep2 ...
  #- source activate test-environment
  #- python setup.py install

script:
  # Your test script goes here
  - python test.py
  - coverage run test.py

# Push the results back to codecov
after_success:
  - codecov
